"""modify chapter table

Revision ID: 7771ceb17089
Revises: b2a284ea7bff
Create Date: 2018-01-02 16:24:36.060833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7771ceb17089'
down_revision = 'b2a284ea7bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('video_duration', sa.String(length=24), nullable=True))
    op.drop_column('chapter', 'vedio_duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('vedio_duration', mysql.VARCHAR(length=24), nullable=True))
    op.drop_column('chapter', 'video_duration')
    # ### end Alembic commands ###
