"""fix chapter table

Revision ID: e032f19a7b7c
Revises: 7771ceb17089
Create Date: 2018-01-02 16:27:14.644909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e032f19a7b7c'
down_revision = '7771ceb17089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('video_url', sa.String(length=256), nullable=True))
    op.drop_column('chapter', 'vedio_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('vedio_url', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('chapter', 'video_url')
    # ### end Alembic commands ###
